version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2-node
    steps:
      - checkout
      - run:
          name: Getting the Code
          command: ls -al
      - ruby/install-deps
      - run:
          name: Check Version
          command: ruby --version
  # test:
  #   parallelism: 2
  #   docker:
  #     - image: cimg/ruby:3.2.2-node
  #   steps:
  #     - checkout
  #     - ruby/install-deps
      # Run rspec
      # - ruby/rspec-test
  db:
    working_directory: ~/MTM-Bulletin-Board
    docker:
      - image: cimg/ruby:3.2.2-node
        environment:
          BUNDLER_VERSION: 2.4.19
          RAILS_ENV: test
          DB_USER: dbuser
          DB_PASSWORD: dbuser
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:8.0
        command: |
          mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_DATABASE: Test-BulletinBoard
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: dbuser
          MYSQL_PASSWORD: dbuser
          MYSQL_ROOT_HOST: '%'
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 3m
      - run:
          name: Install bundle
          command: bundle install
      - run:
          name: Setup DB
          command: |
            bundle exec rails db:create db:migrate
      - run:
          name: RSpec
          command: bundle exec rspec --format progress spec
          # command: bundle exec rspec ./spec/requests/series/series_spec.rb
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build
      - db:
          requires:
            - build
